// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQdEken9c01POw22qf7Bn8lL7lE99Qk-Q',
    appId: '1:696266026073:web:bdbaa790114d6c6f68d548',
    messagingSenderId: '696266026073',
    projectId: 'moapp-d8423',
    authDomain: 'moapp-d8423.firebaseapp.com',
    storageBucket: 'moapp-d8423.appspot.com',
    measurementId: 'G-KQ8NQFXEJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS28-EwaWJNfchozrnc4WLVHhqwTK0Lo8',
    appId: '1:696266026073:android:51ba9b4774939f0e68d548',
    messagingSenderId: '696266026073',
    projectId: 'moapp-d8423',
    storageBucket: 'moapp-d8423.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrDmF5ycrFDHmxqqfNj5A7ISQyn4yksvc',
    appId: '1:696266026073:ios:1bdc9ae13e9bac4e68d548',
    messagingSenderId: '696266026073',
    projectId: 'moapp-d8423',
    storageBucket: 'moapp-d8423.appspot.com',
    iosBundleId: 'com.example.fitzapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrDmF5ycrFDHmxqqfNj5A7ISQyn4yksvc',
    appId: '1:696266026073:ios:83027bee2b24064768d548',
    messagingSenderId: '696266026073',
    projectId: 'moapp-d8423',
    storageBucket: 'moapp-d8423.appspot.com',
    iosBundleId: 'com.example.fitzapp.RunnerTests',
  );
}
